# (C) Copyright IBM Corp. 2020
# SPDX-License-Identifier: Apache-2.0

name: Linux for Health Publish Snapshot Image
description: Publishes a snapshot image to linuxforhealth/connect when a commit is pushed to the Linux for Health master branch.

on:
  push:
    branches:
      - master
jobs:
  push_to_registry:
    name: Publish Snapshot Image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout LFH Project
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64,linux/s390x
          tags: linuxforhealth/connect:snapshot
